from Houses import *
houes1=Villa(600,'in aleppo','super deluxe')
houes2=Home(120,'in jablh',"2th")
print(houes1)
print(houes2)
print()
houes1.adjective()
houes2.adjective()
print()
print("house1:")
print(houes1.getarea())
print(houes1.getpositions())
print()
print("house2:")
print(houes2.getarea())
print(houes2.getpositions())
